version: '3.3'
volumes:
    usermanagement_db_data:
    ordermanagement_db_data:
services: 
    usermanagement:
        build: 
            dockerfile: usermanagement/Dockerfile
            context: .        
        restart: always
        ports: 
            - "3000:3000"
        depends_on: 
            - usermanagement_db
    usermanagement_db:
        image: mongo 
        volumes: 
            - usermanagement_db_data:/data/db
        restart: always        
    ordermanagement:
        build: 
            dockerfile: ordermanagement/Dockerfile
            context: .
        restart: always        
        ports: 
            - "3001:3000"
        depends_on: 
            - ordermanagement_db
    ordermanagement_db:
        image: mongo  
        volumes: 
            - ordermanagement_db_data:/data/db
        restart: always   