version: '3.3'
services: 
    usermanagementservice:
        build: 
            dockerfile: UserManagement/Dockerfile
            context: .      
        restart: always
        ports: 
            - "3000:3000"
        depends_on: 
            - usermanagementservice_db
    usermanagementservice_db:
        image: mongo 
        restart: always        
    ordermanagementservice:
        build: 
            dockerfile: OrderManagement/Dockerfile
            context: .
        restart: always
        ports: 
            - "3001:3000"
        depends_on: 
            - ordermanagementservice_db
    ordermanagementservice_db:
        image: mongo  
        restart: always        