pipeline{
    agent any
    stages{
        stage("get checkout"){
            steps{
                sh "git 'https://github.com/atuljain1383/apis.git'"
            }
        }
        stage("build"){
            steps{
                echo 'build started...'
            }
        }
        stage("create images"){
            steps{
                sh "docker-compose -d --build"
            }
        }
        stage('Push Docker Image'){
           steps{
               sh "docker login -u atuljain1383 -p Ishika@2sep"
               sh 'docker-compose push'
           }
                
        }        
    }

}