pipeline{
    agent any
    stages{
        stage("get checkout"){
            steps{
                git credentialsId: 'GitHub', url: 'https://github.com/atuljain1383/apis.git'
            }
        }
        stage("build"){
            steps{
                echo 'build started...'
            }
        }
        stage("create images"){
            steps{
                sh "sudo -p  docker-compose build -d"
            }
        }
        stage('Push Docker Image'){
           steps{
               sh "sudo docker login -u atuljain1383 -p Ishika@2sep"
               sh 'sudo docker-compose push'
           }
                
        }        
    }

}