version: '3.3'
services: 
    usermanagement:
        build: 
            dockerfile: Dockerfile
            context: .        
        restart: always
        ports: 
            - "3000:3000"
        depends_on: 
            - usermanagement_db
    usermanagement_db:
        image: mongo               
        restart: always        