@Library('jenkinssharedlibrary') _
microservicepipeline([branchname: "master", 
     giturl: "https://github.com/atuljain1383/apis.git",
     imagename: "atuljain1383/usermanagement:v4", 
     dockerhubuserid: "atuljain1383", 
     dockerhubpassword: "Ishika@2sep", 
     jenkinsdir: "/var/lib/jenkins/workspace/UserManagemenService/services/usermanagement"]
);
